config/routes.rb
Psqlproj::Application.routes.draw do
  resources :videos

  resources :homes

  root :to => 'homes#index'
end

app/models/video.rb
class Video < ActiveRecord::Base
   attr_accessible :video
   has_attached_file :video
   validates_attachment :video, content_type: { content_type: ["video/mp4"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def new
    @video = Video.new
  end
  
  def create
    @video = Video.new(params[:video])
    if @video.save
      redirect_to "/"
    else
      redirect_to :back
    end
  end

  def show
    @video = Video.find(params[:id])
  end

  def index
    @videos = Video.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Psqlproj" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Psqlproj</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "hotels" %></li>
              <li><%= link_to "Search Hotel" %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Video</li>
              <li><%= link_to "Add video", new_video_path %></li>
              <li><%= link_to "List of videos", videos_path %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
      
    </div> <!-- /container -->

  </body>
</html>

app/views/videos/index.html.erb
<div class="panel-body">
  <div class="table-responsive">
    <table class="table table-bordered">
      <tr>
        <th>Video File Name</th>
        <th>Status</th>
      </tr>
      
      <% @videos.each do |video| %>
      <tr>
        <td>
          <%= video.video.name %>
        </td>
        <td>
          <%= link_to "show", video_path(video.id) %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/videos/new.html.erb
<div class="panel-body">
  <%= form_for @video do |f| %>
    <div class="row-fluid">
      <div class="col-sm-12">
        <%= f.file_field :video %>
      </div>
    </div>

    <div class="row-fluid">
      <div class="col-sm-12">
        <%= f.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/videos/show.html.erb
<div class="panel-body">
  <a
    href="<%= @video.video.url %>"
    style="display:block; height: 300px; width: 640px; z-index: 100px;"
    id="player">
  </a>

  <%= javascript_include_tag "flowplayer-3.2.6.min"  %>

  <script type="text/javascript">
    flowplayer("player", {src: "/assets/flowplayer/flowplayer-3.2.6.swf", wmode: "transparent"},
    {clip: {
        autoPlay: false,
        autoBuffering: true
      }}
    );
  </script>

</div>

<br/><br/>

<div class="panel-body">
<%#*<script type="text/javascript">jwplayer.key = "u223Cjasxi+MBL4pWJhKALFekqeIHP1TWEWUWg==";</script>%>
  <div id="video"></div>
  <script type="text/javascript">
    jwplayer("video").setup({
      flashplayer: "/myassets/jwplayer/jwplayer.flash.swf",
      file: "<%= @video.video.url %>",
      image: "/myassets/images/rails.png",
      height: 300,
      skin: "/skins/five.xml",
<%#*advertising: {%>
<%#*client: "vast",%>
<%#*tag: "http://adserver.com/vastTag.xml"%>
<%#*},%>
      width: 640,
      analytics: {
        enabled: false,
        cookies: false
      }
    });
  </script>

</div>